name: fluter_app
description: "A new Flutter project."
publish_to: 'none' # Remove esta linha se quiser publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Utilitários
  intl: ^0.20.2
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  path_provider: ^2.0.11
  path: ^1.9.0
  shared_preferences: ^2.2.3
  http: ^1.2.1
  image: ^4.0.17
  csv: ^6.0.0
  share_plus: ^7.2.2
  excel: ^4.0.6
  tflite_flutter: ^0.11.0
  sqflite: ^2.3.3+1


  # Câmera e visão computacional
  camera: ^0.11.0
  opencv_dart: ^1.0.3 

  # Firebase
  firebase_core: ^2.31.0
  firebase_auth: ^4.16.0
  firebase_app_check: ^0.2.2
  # Outros
  file_picker: ^10.3.2
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0

flutter:
  uses-material-design: true
  assets:
      - assets/models/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
